import clases
Mazo=clases.genera_mazo()
print(f"Mazo generado: {Mazo}")
print(f"numero de cartas en el mazo {len(Mazo)}")
corazones, treboles, diamantes, picas = clases.organizar_mazo(Mazo)
print("mazo separado")
print(f"Corazones: {corazones}")
print(f"Treboles: {treboles}")
print(f"Diamantes: {diamantes}")
print(f"Picas: {picas}")
corazones=clases.insertion_sort(corazones)
treboles=clases.insertion_sort(treboles)
diamantes=clases.insertion_sort(diamantes)
picas=clases.insertion_sort(picas)
print("mazo organizado")
print(f"Corazones: {corazones}")
print(f"Treboles: {treboles}")
print(f"Diamantes: {diamantes}")
print(f"Picas: {picas}")